name: Windows - LiteManager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building...
    runs-on: windows-latest
    timeout-minutes: 9999  # Long timeout, consider optimizing based on needs
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat

      - name: Update IP Location Every 30 Minutes
        run: |
          # Create a script to update IP location
          echo "ping google.com" > UpdateIP.bat
          echo "timeout /t 1800" >> UpdateIP.bat
          echo "ping google.com" >> UpdateIP.bat
          start cmd /c UpdateIP.bat
